pipeline{
    agent any

    parameters{
        choice(name: 'terraformAction',choices: ['apply','destroy'],description: 'Choose your terraform action')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    
    stages{
        stage('Checkout'){
            steps{
                dir("terraform"){
                    git url: 'https://github.com/afeef96867-hub/Itkannadigaru-chatbot.git', branch: 'Iac-devenv'
                }
            }
        }

        stage('Terraform Init'){
            steps{
                sh 'cd terraform/eks && terraform init'
            }
        }

        stage('Terraform Plan'){
            steps{
                sh 'cd terraform/eks && terraform plan -out tfplan'
                sh 'cd terraform/eks && terraform show -no-color tfplan > tfplan.txt'
            }
        }

        stage('Approval'){
            steps{
                script{
                    def plan = readFile 'terraform/eks/tfplan.txt'
                    input message: "Do you want to proceed?",
                    parameters: [text(name: 'Plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply or Destroy'){          
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                        sh 'cd terraform/eks && terraform apply -input=false tfplan'
                    } else {
                        sh 'cd terraform/eks && terraform destroy -auto-approve'
                    }
                }
            }
        }

        stage('Backup-stage'){
            steps{
                sh '''
                export PATH=$PATH:/snap/bin
                cd terraform/eks
                aws s3 cp terraform.tfstate s3://itkannadogaru-terraform-tf-backup/chat-bot/dev-eks/terraform.tfstate
                '''
            }
        }
    }
    
}

